/*
 * IDA 9.3 New API Reference
 * 
 * Generated by analyzing libida.so symbol exports from IDA Pro 9.33 beta.
 * Signatures verified via Hex-Rays decompilation.
 * 
 * This file documents NEW APIs in IDA 9.3 that are NOT in the 9.2 SDK.
 * It is a REFERENCE DOCUMENT, not meant to be included directly.
 * 
 * Usage: When you need a 9.3 API, copy the relevant declaration to your
 * source file with appropriate IDA headers already included.
 */

#if 0  // Reference only - do not compile

// =====================================================================
// DIRTREE BULK OPERATIONS
// =====================================================================

// dirtree_bulk_move @ 0x77A230
// Moves multiple entries to a destination folder
dterr_t dirtree_bulk_move(
    dirtree_impl_t *d,
    const dirtree_selection_t *entries,
    diridx_t dst_folder,
    uint32 flags);

// dirtree_bulk_remove @ 0x77CBD0
dterr_t dirtree_bulk_remove(
    dirtree_impl_t *d,
    const dirtree_selection_t *entries);

void dirtree_make_cursor(
    dirtree_cursor_t *out,
    diridx_t parent,
    size_t rank);

// =====================================================================
// EVENT HANDLER SYSTEM
// =====================================================================

struct event_source_t;
typedef int (*event_handler_t)(void *ud, int event_id, va_list va);

// Verified: both args are qvector-based objects with bidirectional linkage
// source: +0=vtable, +8=handlers_data, +16=handler_count, +24=capacity
// handler: +0=vtable, +8=sources_data, +16=source_count, +24=capacity
// handler vtable[2] (offset +16) is the dispatch callback
bool bind_event_handler(event_source_t *source, event_handler_t *handler);
bool unbind_event_handler(event_source_t *source, event_handler_t *handler);

// unbind_event_handler_all @ 0x82CCD0
void* unbind_event_handler_all(event_source_t *source);

void unbind_event_source_all(event_source_t *source);
// Verified: iterates handlers, calls handler->vtable[2](handler, event_id, &data_copy)
int event_source_dispatch(event_source_t *source, int event_id, const void *event_data);

// =====================================================================
// DIRTREE EVENT HANDLERS
// =====================================================================

// dirtree_add_event_handler @ 0x777BE0 (thunk to bind_event_handler)
void dirtree_add_event_handler(dirtree_impl_t *d, event_handler_t handler, void *ud);
void dirtree_remove_event_handler(dirtree_impl_t *d, event_handler_t handler);

// reset_dirtree @ 0x77A6A0
void reset_dirtree(dirtree_impl_t *d);

// =====================================================================
// DEREF CHAIN VISUALIZATION (Hex-Rays stack view)
// =====================================================================

struct ctree_item_t;
struct deref_chain_t;

// generate_deref_chain @ 0x3FEB70
uint64 generate_deref_chain(
    const ctree_item_t *item,
    uint32 flags,
    deref_chain_t *chain,
    bool include_last);

// get_deref_color @ 0x3FEB20 - returns COLOR_* constant (5, 12, 14, 15, or 31)
int get_deref_color(void);

// =====================================================================
// VAULT/TEAMS APIs
// =====================================================================

struct vault_server_t;
struct vault_filesys_t;

// Verified: first arg is qstring output, NOT const char* return
void vault_errstr(qstring *out, int err);
// Verified: takes char (action enum), returns static string
const char* vault_get_action_name(int action);
// Verified: takes 6 int args (varargs-like), returns qstring
void vault_get_revision_postfix(qstring *out);
bool vault_is_valid_email(const char *email);
bool vault_is_valid_name(const char *name);

// get_vault_server @ 0x8C2E00 - returns singleton
vault_server_t* get_vault_server(void);
// Verified: takes 3 args (a1=output, a2=server_url, a3=flags)
void* get_vault_filesys(void *out, const char *server, int flags);

// =====================================================================
// INDEXER APIs (NEW in 9.3) - Fast database-wide search
// =====================================================================

// indexer_is_enabled @ 0x432830
// Returns true if the database indexer is enabled
bool indexer_is_enabled(void);

// indexer_match_all @ 0x432BF0
// Synchronous search - blocks until complete
// pattern: search pattern
// flags: search flags
// results: output result vector (use free_result_vec to free)
bool indexer_match_all(const char *pattern, uint32 flags, void *results);

// indexer_match_all_async @ 0x437310
// Asynchronous search - returns immediately, calls callback on completion
// pattern: search pattern
// flags: search flags  
// callback: called with results when search completes
// userdata: passed to callback
void indexer_match_all_async(
    const char *pattern,
    uint32 flags,
    void *callback,
    void *userdata);

// free_result_vec @ 0x433320
// Frees result vector from indexer_match_all
void free_result_vec(void *result_vec);

// indexer_match @ 0x432C20
// Single match search. Verified: 4 args from decompilation.
// Returns first match only.
bool indexer_match(const char *pattern, uint32 flags, qstring *result_str, void *match_info);

// indexer_get_subindex @ 0x432E30
void* indexer_get_subindex(int index);

// indexer_register_subindex @ 0x434200
bool indexer_register_subindex(void *subindex);

// indexer_unregister_subindex @ 0x432DC0
void indexer_unregister_subindex(void *subindex);

// =====================================================================
// SEARCH UTILITIES (NEW in 9.3)
// =====================================================================

// get_search_utils @ 0x5084C0
// Returns singleton search utility object
void* get_search_utils(void);

// regex_match @ 0x67BA90
// Matches pattern against string
// pattern: regex pattern
// str: string to match
// case_sensitive: true for case-sensitive match
int regex_match(const char *pattern, const char *str, bool case_sensitive);

// =====================================================================
// SEARCH FUNCTIONS - VERIFIED SIGNATURES
// =====================================================================

// find_text @ 0x67B7D0
// Wrapper that calls internal search function via linearray
// CRITICAL: Does NOT support SEARCH_NEXT flag!
// You MUST manually advance ea with next_head(ea, end_ea) after each match.
ea_t find_text(ea_t start_ea, int y, int x, const char *ustr, int sflag);

// search @ 0x67B6A0 - Low-level text search
// ud: line array userdata
// start: starting place (modified on success)
// end: ending place
// startx: starting X coordinate (modified on success)
// str: search string
// sflag: SEARCH_* flags
// Returns: 0=not found, 1=found, 2=cancelled, 3=bad regex
int search(void *ud, place_t *start, const place_t *end, int *startx, const char *str, int sflag);

// bin_search @ 0x675AC0 - Binary pattern search
// start, end: address range
// patterns: compiled binary patterns (from parse_binpat_str)
// flags: BIN_SEARCH_* flags
// match_idx: which pattern matched (output)
ea_t bin_search(ea_t start, ea_t end, void *patterns, int flags, ea_t *match_idx);

// find_binary @ 0x67A870 - High-level binary search wrapper
// start, end: address range
// pattern: pattern string (e.g., "48 8B ? ? 90")
// radix: number base for pattern (usually 16)
// sflag: SEARCH_* flags
// features: additional feature flags
ea_t find_binary(ea_t start, ea_t end, const char *pattern, int radix, int sflag, int features);

// find_reg_access @ 0x6754D0 - Find register read/write
// out: output register access info
// start_ea, end_ea: address range
// regname: register name (e.g., "rax", "eax")
// sflag: SEARCH_* flags (use SEARCH_USE for reads, SEARCH_DEF for writes)
ea_t find_reg_access(void *out, ea_t start_ea, ea_t end_ea, const char *regname, int sflag);

// =====================================================================
// MISC
// =====================================================================

// Verified: takes qstring* output, internally calls idadir(0)
void get_install_root(qstring *out);
bool get_nlist_demangled_name(qstring *out, size_t idx);
bool is_get_nlist_demangled_name_supported(void);

// =====================================================================
// TYPE SYSTEM
// =====================================================================

// tinfo_t::build_anon_type_name @ 0x6AFCD0
bool tinfo_t__build_anon_type_name(qstring *out, const tinfo_t *type);

// udm_t::compare_with @ 0x5538F0 - returns -1, 0, or 1
int udm_t__compare_with(const udm_t *a, const udm_t *b, uint32 flags);

// udt_type_data_t::deduplicate_members @ 0x537BA0
int udt_type_data_t__deduplicate_members(udt_type_data_t *udt);

// =====================================================================
// IMPORT TABLE (NEW in 9.3, PE-only)
// =====================================================================

// import_info_t — Reverse-engineered from libida.so:sub_627110
// Cross-verified against IDAPython SWIG bindings (import_entry_t in ida_nalt.py)
//
// Layout confirmed via:
//   1. Decompiled get_import_entry wrapper @ 0x627910
//   2. Decompiled inner function sub_627110 (hash table cache + netnode slow path)
//   3. Internal cache node: operator new(0x48) = 72 bytes
//      Node+0:  next_ptr   (linked list)
//      Node+8:  idx        (uint64 key)
//      Node+16: name       (qstring, 24 bytes)
//      Node+40: ordinals   (qvector<uval_t>, 24 bytes)
//      Node+64: mod_index  (int32, 4 bytes)
//      Node+68: padding    (4 bytes → 72 total)
//   4. IDAPython field names match: name, ordinals, mod_index
//
// The function looks up import entry by index:
//   - FAST PATH: hash table cache (std::unordered_map keyed by idx)
//   - SLOW PATH: netnode scan across all modules
//     - Tag 'S' (83): import name (supstr)
//     - Tag 'A' (65): ordinal→EA mapping (altvals)
//     - Tag 'O' (79): ordinal reverse lookup
//     - sub_3BD6E0: idx → netnode EA (adds base offset)
//     - sub_3BD7D0: netnode EA → idx (subtracts base offset)

struct import_info_t
{
    qstring name;              ///< name of import entry (may be empty for ordinal-only imports)
    qvector<uval_t> ordinals;  ///< import ordinals (may be empty for name-only imports)
    int mod_index;             ///< module index (use with get_import_module_name())
};

// get_import_entry @ 0x627910 — PE-only (per IDA 9.3 release notes)
// Wrapper: calls sub_627110(global_state+1672, out, idx)
// Returns true if import entry found, false otherwise
bool get_import_entry(import_info_t *out, size_t idx);

// =====================================================================
// BOOKMARKS
// =====================================================================

struct bookmark_t;
// Verified: 4 args (bookmarks, lochist_entry output, inode, index). Returns uint or -1.
uint32 bookmarks_t_get_by_inode(void *bookmarks, void *lochist_out, uint64 inode, int index);

// =====================================================================
// WIDE VALUE APIs (NEW in 9.3) - 64-bit values stored at addresses
// =====================================================================

// Stores/retrieves values via netnode supval with tag 'A' (65).
// Internally adds 1 on store, subtracts 1 on read (so 0 is a valid value).

// get_wide_value @ 0x3BD930
// Returns the wide value at ea, or -1 (BADADDR) if not set.
// Signature: sval_t get_wide_value(ea_t ea)
idaman sval_t ida_export get_wide_value(ea_t ea);

// set_wide_value @ 0x3BD9D0
// Sets the wide value at ea.
// Signature: void set_wide_value(ea_t ea, sval_t value)
idaman void ida_export set_wide_value(ea_t ea, sval_t value);

// del_wide_value @ 0x3BDA60
// Deletes the wide value at ea.
// Signature: void del_wide_value(ea_t ea)
idaman void ida_export del_wide_value(ea_t ea);

// =====================================================================
// JUMPTABLE INFO APIs (NEW in 9.3) - Extended jump table metadata
// =====================================================================

// Stores a pair of {ea_t table_ea, ea_t size} in netnode supval tag 'S'/4.
// Distinct from switch_info_t which handles the full switch idiom.

// get_jumptable_info @ 0x59D690
// Retrieves jump table info: out[0] = table_ea, out[1] = size
// Returns 16 on success, -1 on failure.
// Signature: ssize_t get_jumptable_info(ea_t out[2], ea_t ea)
idaman ssize_t ida_export get_jumptable_info(ea_t out[2], ea_t ea);

// set_jumptable_info @ 0x59D7A0
// Sets jump table info: info[0] = table_ea, info[1] = size
// Signature: void set_jumptable_info(ea_t ea, const ea_t info[2])
idaman void ida_export set_jumptable_info(ea_t ea, const ea_t info[2]);

// del_jumptable_info @ 0x59D830
// Deletes the jump table info at ea.
// Signature: void del_jumptable_info(ea_t ea)
idaman void ida_export del_jumptable_info(ea_t ea);

// create_func_table @ 0x44F6D0
// Creates a function table (internal). No arguments.
// Signature: void create_func_table(void)
idaman void ida_export create_func_table(void);

// =====================================================================
// METADATA BACKUP/RESTORE APIs (NEW in 9.3) - Function analysis state
// =====================================================================

// These work on the current cursor address internally (get_func(screen_ea)).
// backup saves function metadata to a netnode blob (tag 'S'/1085440).
// revert restores from that blob via apply_metadata.

// backup_metadata @ 0x7D9C30
// Backs up current function's metadata (names, types, comments, etc.)
// Works on function at current cursor.
// Signature: bool backup_metadata(ea_t ea)
idaman bool ida_export backup_metadata(ea_t ea);

// has_backup_metadata @ 0x7D74E0
// Checks if the function at ea has backed-up metadata.
// Signature: bool has_backup_metadata(ea_t ea)
idaman bool ida_export has_backup_metadata(ea_t ea);

// revert_metadata @ 0x7DA050
// Restores function metadata from backup blob.
// Returns true on success.
// Signature: bool revert_metadata(ea_t ea)
idaman bool ida_export revert_metadata(ea_t ea);

// apply_metadata @ 0x7D9C50
// Applies metadata to a function. Complex internal struct.
// ea: function start address
// metadata: serialized metadata blob
// flags: 1 = clear existing, 0x10000 = flag control
// Signature: void apply_metadata(ea_t ea, const void *metadata, int flags)
idaman void ida_export apply_metadata(ea_t ea, const void *metadata, int flags);

// calc_func_metadata @ 0x7D7840
// Calculates complete function metadata (very complex - 234 local vars).
// md5_out: 16-byte MD5 hash output (can be NULL)
// metadata_out: output metadata structure
// func: function to analyze
// callback: optional callback for extra metadata (can be NULL)
// Returns: function size in bytes
// Signature: uint64 calc_func_metadata(void *md5_out, void *metadata_out,
//                                       func_t *func, void *callback)
idaman uint64 ida_export calc_func_metadata(
    void *md5_out,
    void *metadata_out,
    func_t *func,
    void *callback);

// =====================================================================
// UNDOCUMENTED INTERNAL APIs - Reverse-engineered from libida.so
// These are exported symbols with NO SDK declaration.
// Signatures verified via Hex-Rays decompilation of IDA 9.33 binary.
// =====================================================================

// ---- HTTP / Network ----

// http_request @ libida.so+0x7C3EA0
// Makes an HTTP request using IDA's built-in HTTP client.
// Verified via decompilation of libida.so directly.
// Signature: int http_request(http_request_config_t *config, ...)
// Config struct layout (verified from field accesses in decompiled code):
//   +0:   const char *url          (QWORD)
//   +8:   int method               (DWORD - 0=GET, 1=POST, etc)
//   +12:  uint16 port              (WORD)
//   +16:  qstring *headers         (QWORD)
//   +24:  const char *body         (QWORD)
//   +40:  qstring *response_hdrs   (QWORD ptr)
//   +72:  qstring *response_body   (QWORD)
//   +88:  void *output_buffer      (QWORD - for file download)
//   +96:  size_t output_size       (QWORD)

// http_get_file @ libida.so
// Downloads a file via HTTP.
// Wrapper around http_request for simple GET-to-file operations.

// upload_idb @ libida.so
// Uploads IDB to Lumina/vault server.
// upload_idb(char *path, const char *name, const char *version, ...)
// 10 arguments total - complex internal struct.

// ---- License Manager ----

// get_license_manager @ libida.so+0x395BB0
// Returns pointer to license manager singleton (vtable-based object).
// License manager layout:
//   +0:   vtable pointer
//   +176: license data pointer (void*)
//   +184: license data size (size_t)
// Vtable methods:
//   [6]  (offset 48): method(self, qstring *out, int flags) - get license info
//   [11] (offset 88): method(self, int, int) - query license state
// Signature: void* get_license_manager(void)

// get_borrowed_license @ libida.so+0x8A27C0
// Gets borrowed license information.

// get_mac_addresses @ libida.so+0x835840
// Gets MAC addresses of network interfaces (for license binding).
// Signature: void get_mac_addresses(qstrvec_t *out)

// ---- Process Execution ----

// launch_process @ libida.so+0x840E80
// Launches an external process.
// Takes a launch_process_params_t struct (80 bytes, 5 x __m128i).
// Signature: int launch_process(const launch_process_params_t *params)

// capture_process_output @ libida.so+0x841F90
// Captures stdout/stderr from a child process.
// Verified: 5 args (not 4).
// int capture_process_output(const char *cmdline, qstring *stdout_out,
//                            qstring *stderr_out, int timeout_ms, int flags)

// check_process_exit @ 0x840BB0
// Checks if a launched process has exited.

// =====================================================================
// NOTIFICATION/EVENT SYSTEM
// =====================================================================

// append_notification_point @ 0x4B3A30
// Appends a notification callback to the notification chain.
// Used internally to register for IDB events.

// =====================================================================
// CRC/HASHING
// =====================================================================

// calc_crc32 @ 0x824BA0
// Calculates CRC32 of a buffer.
// uint32 calc_crc32(uint32 init_crc, const void *buf, size_t size)

// calc_file_crc32 @ 0x824BB0
// Calculates CRC32 of the input file.
// uint32 calc_file_crc32(void)

// =====================================================================
// IDS FILE OPERATIONS (FLIRT signature database)
// =====================================================================

// open_ids_file @ (via nm)
// Opens an IDS (ID Signature) file for reading.

// close_ids_file @ 0x5DF310
// Closes an IDS file.

// =====================================================================
// MISC
// =====================================================================

// create_hit_counter @ 0x832DE0
// Creates a performance hit counter for profiling.

// create_zstd_linput @ 0x84C7C0
// Creates a zstd-compressed linput (for reading compressed files).

// compare_bpt_locs @ 0x3AEA30
// Compares two breakpoint locations.

// basic_parser_parse @ 0x7A5FE0
// Low-level parser for basic syntax (used by IDC compiler).

// dto_copy_from_inf @ 0x633340
// Copies database transfer object from idainfo.

// dto_copy_to_inf @ 0x633040
// Copies database transfer object to idainfo.

// dto_init @ 0x62E240
// Initializes a database transfer object.

// build_plugin_options @ 0x826E20
// Builds plugin options string.

// addr_from_tag @ 0x3DED20
// Extracts an address from a color tag in disassembly line.

#endif // Reference only
