// IDA 9.3 New API Stubs
// Generated by analyzing libida.so symbol exports
// Signatures need verification via decompilation

#pragma once
#include <pro.h>
#include <dirtree.hpp>

//----------------------------------------------------------------------
// Dirtree bulk operations (new in 9.3)
//----------------------------------------------------------------------

// TODO: Verify signature by decompiling dirtree_bulk_move in libida.so
idaman dterr_t ida_export dirtree_bulk_move(
    dirtree_impl_t *d,
    const dirtree_selection_t *selection,
    const char *dest_path);

idaman dterr_t ida_export dirtree_bulk_remove(
    dirtree_impl_t *d,
    const dirtree_selection_t *selection);

idaman void ida_export dirtree_make_cursor(
    dirtree_cursor_t *out,
    diridx_t parent,
    size_t rank);

//----------------------------------------------------------------------
// Event handler system (new in 9.3)
//----------------------------------------------------------------------

// TODO: Identify callback signature from decompilation
typedef int (*event_handler_t)(void *ud, int event_id, va_list va);

idaman void ida_export bind_event_handler(/* unknown */);
idaman void ida_export unbind_event_handler(/* unknown */);
idaman void ida_export unbind_event_handler_all(/* unknown */);
idaman void ida_export unbind_event_source_all(/* unknown */);
idaman void ida_export event_source_dispatch(/* unknown */);

//----------------------------------------------------------------------
// Dirtree event handlers (new in 9.3)
//----------------------------------------------------------------------

idaman void ida_export dirtree_add_event_handler(dirtree_impl_t *d, /* handler */);
idaman void ida_export dirtree_remove_event_handler(dirtree_impl_t *d, /* handler */);
idaman void ida_export reset_dirtree(dirtree_impl_t *d);

//----------------------------------------------------------------------
// Deref chain visualization (new in 9.3)
//----------------------------------------------------------------------

// For stack view dereferencing feature
idaman bool ida_export generate_deref_chain(/* output, ea, ... */);
idaman uint32 ida_export get_deref_color(/* ... */);

//----------------------------------------------------------------------
// Vault/Teams APIs (new in 9.3)
//----------------------------------------------------------------------

idaman const char* ida_export vault_errstr(int err);
idaman const char* ida_export vault_get_action_name(int action);
idaman const char* ida_export vault_get_revision_postfix(void);
idaman bool ida_export vault_is_valid_email(const char *email);
idaman bool ida_export vault_is_valid_name(const char *name);
idaman void* ida_export get_vault_server(void);
idaman void* ida_export get_vault_filesys(void);

//----------------------------------------------------------------------
// Misc new APIs
//----------------------------------------------------------------------

idaman const char* ida_export get_install_root(void);
idaman bool ida_export get_nlist_demangled_name(qstring *out, /* ... */);
idaman bool ida_export is_get_nlist_demangled_name_supported(void);
idaman void* ida_export get_search_utils(void);
idaman void ida_export free_result_vec(/* result_vec_t* */);
idaman bool ida_export indexer_match_all_async(/* ... */);

//----------------------------------------------------------------------
// Type system improvements
//----------------------------------------------------------------------

idaman bool ida_export tinfo_t__build_anon_type_name(qstring *out, /* ... */);
idaman int ida_export udm_t__compare_with(const udm_t *a, const udm_t *b);
idaman void ida_export udt_type_data_t__deduplicate_members(udt_type_data_t *udt);

//----------------------------------------------------------------------
// Import table
//----------------------------------------------------------------------

idaman bool ida_export get_import_entry(/* import_info_t *out, size_t idx */);

//----------------------------------------------------------------------
// Bookmarks
//----------------------------------------------------------------------

idaman bool ida_export bookmarks_t_get_by_inode(/* bookmark_t *out, inode_t */);

